name: NightlyTests
on:
  workflow_dispatch:
    inputs:
      branches:
        required: false
        type: string
        description: "Array of branches to run: ['21','master'].  Defaults to NIGHTLYTEST_BRANCHES"
      group_list:
        required: false
        type: string
        description: "Array of test groups to run: ['ari1','channels'].  Defaults to NIGHTLYTEST_LIST"

  schedule:
#            Monday-Saturday 2am
    - cron: '0 2 * * 1-6'

jobs:
  NightlyTests:
    name: NightlyTests
    uses: asterisk/asterisk-ci-actions/.github/workflows/AsteriskNightlyTest.yml@main
    with:
      branches:   ${{ inputs.branches || vars.NIGHTLYTEST_BRANCHES }}
      group_list: ${{ inputs.group_list || vars.NIGHTLYTEST_LIST }}
      realtime:   false
